<?php
    $addressData = $block->getAddressData();
?>
<form class="form-address-edit" action="<?= $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="* Required Fields" novalidate="novalidate">
    <fieldset class="fieldset">
        <legend class="legend"><span>Contact Information</span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>First Name</span>
            </label>

            <div class="control">
                <input value="<?= ($addressData) ? $addressData->getFirstname() : '' ?>" type="text" id="firstname" name="firstname" title="First Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>
        <div class="field field-name-lastname required">
            <label class="label" for="lastname">
                <span>Last Name</span>
            </label>

            <div class="control">
                <input value="<?= ($addressData) ? $addressData->getLastname() : '' ?>" type="text" id="lastname" name="lastname" title="Last Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>


        <div class="field company ">
            <label for="company" class="label">
                <span>Company</span>
            </label>
            <div class="control">
                <input value="<?= ($addressData) ? $addressData->getCompany() : '' ?>" type="text" name="company" id="company" title="Company" class="input-text ">
            </div>
        </div>


        <div class="field telephone required">
            <label for="telephone" class="label">
        <span>
            Phone Number        </span>
            </label>
            <div class="control">
                <input value="<?= ($addressData) ? $addressData->getTelephone() : '' ?>" type="text" name="telephone" id="telephone" value="" title="Phone Number" class="input-text">
            </div>
        </div>


    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span>Address</span></legend><br>
        <div class="field street required">
            <label for="street_1" class="label">
                <span>Street Address</span>
            </label>
            <div class="control">
                <input value="<?= ($addressData) ? $addressData->getStreet() : '' ?>" type="text" name="street[]" value="" title="Street Address" id="street_1" class="input-text required-entry" aria-required="true">
                <div class="nested" style="display: none">
                    <div class="field additional">
                        <label class="label" for="street_2">
                            <span>Street Address 2</span>
                        </label>
                        <div class="control">
                            <input type="text" name="street[]" value="" title="Street Address 2" id="street_2" class="input-text " aria-required="true">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="field city required">
            <label class="label" for="city"><span>City</span></label>
            <div class="control">
                <input type="text" name="city" value="<?= ($addressData) ? $addressData->getCity() : '' ?>" title="City" class="input-text required-entry" id="city" aria-required="true">
            </div>
        </div>

        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                        class="validate-select" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="<?= ($addressData) ? $addressData->getRegion() : '' ?>"
                       title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $block->escapeHtmlAttr(($addressData) ? $addressData->getPostcode() : '') ?>"
                       title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                       id="zip"
                       class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect(($addressData) ? $addressData->getCountryId() : null) ?>
            </div>
        </div>

        <div class="field choice set billing">
            <input type="checkbox" id="primary_billing" name="is_billing" value="1" class="checkbox" <?= ($addressData && $addressData->getIsBilling()) ? 'checked' : '' ?>>
            <label class="label" for="primary_billing">
                <span><?= $block->escapeHtml(__('Use as company billing address')) ?></span>
            </label>
        </div>

    </fieldset>
    <div class="actions-toolbar">
        <input type="hidden" name="address_id" id="address_id" value="<?php echo $block->getIdAddress() ?>" >
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="Save Address">
                <span>Save</span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= ($addressData) ? $addressData->getRegionId() : (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>