<?php
$addressData = $block->getAddressData();
?>
<form class="b2b-form-edit-account b2b-form-address-edit" action="<?= $block->getPostActionUrl() ?>" method="post" id="b2b-form-validate" enctype="multipart/form-data" data-hasrequired="* Required Fields" novalidate="novalidate">
    <fieldset class="b2b-info b2b-fieldset">
        <legend class="b2b-legend"><span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span></legend>
        <?= $block->getBlockHtml('formkey') ?>
        <div class="b2b-field-name-firstname b2b-required">
            <label class="b2b-label" for="firstname">
                <span><?php /* @escapeNotVerified */ echo __('First Name') ?></span>
            </label>

            <div class="b2b-control">
                <input value="<?= ($addressData) ? $addressData->getFirstname() : '' ?>" type="text" id="b2b-firstname" name="firstname" title="First Name" class="b2b-input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>
        <div class="b2b-field b2b-field-name-lastname b2b-required">
            <label class="b2b-label" for="lastname">
                <span><?php /* @escapeNotVerified */ echo __('Last Name') ?></span>
            </label>

            <div class="b2b-control">
                <input value="<?= ($addressData) ? $addressData->getLastname() : '' ?>" type="text" id="b2b-lastname" name="lastname" title="Last Name" class="b2b-input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>
        <hr class="b2b-clear-both-invisible">


        <div class="b2b-field b2b-company b2b-required">
            <label for="company" class="b2b-label">
                <span><?php /* @escapeNotVerified */ echo __('Company') ?></span>
            </label>
            <div class="b2b-control">
                <input value="<?= ($addressData) ? $addressData->getCompany() : '' ?>" type="text" name="company" id="b2b-company" title="Company" class="b2b-input-text">
            </div>
        </div>


        <div class="b2b-field b2b-telephone b2b-required">
            <label for="telephone" class="b2b-label">
                <span><?php /* @escapeNotVerified */ echo __('Phone') ?></span>
            </label>
            <div class="b2b-control">
                <input value="<?= ($addressData) ? $addressData->getTelephone() : '' ?>" type="text" name="telephone" id="b2b-telephone" value="" title="Phone Number" class="b2b-input-text">
            </div>
        </div>

        <div class="b2b-field b2b-email b2b-required">
            <label for="email" class="b2b-label"><span><?php /* @escapeNotVerified */
                    echo __('Email') ?></span></label>
            <div class="b2b-control">
                <input type="text" name="email" id="b2b-email"
                       value="<?= ($addressData) ? $addressData->getEmail() : '' ?>" title="<?php /* @escapeNotVerified */
                echo __('Email') ?>" class="b2b-input-text" data-validate="{required:true}">
            </div>
        </div>
    </fieldset>
    <fieldset class="b2b-fieldset">
        <legend class="b2b-legend"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></legend>
        <div class="b2b-street b2b-required">
            <label for="street_1" class="b2b-label">
                <span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span>
            </label>
            <div class="b2b-field b2b-control">
                <input value="<?= ($addressData) ? $addressData->getStreet() : '' ?>" type="text" name="street[]" value="" title="Street Address" id="b2b-street_1" class="b2b-input-text required-entry" aria-required="true">
                <div class="b2b-nested" style="display: none">
                    <div class="b2b-field additional">
                        <label class="b2b-label" for="street_2">
                            <span>Street Address 2</span>
                        </label>
                        <div class="b2b-control">
                            <input type="text" name="street[]" value="" title="Street Address 2" id="b2b-street_2" class="b2b-input-text " aria-required="true">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="b2b-field b2b-city b2b-required">
            <label class="b2b-label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="b2b-control">
                <input type="text" name="city" value="<?= ($addressData) ? $addressData->getCity() : '' ?>" title="City" class="b2b-input-text required-entry" id="b2b-city" aria-required="true">
            </div>
        </div>

        <div class="b2b-field b2b-region b2b-required">
            <label class="b2b-label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="b2b-control">
                <select id="b2b-region_id" name="region_id"
                        title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                        class="b2b-validate-select" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text"
                       id="b2b-region"
                       name="region"
                       value="<?= ($addressData) ? $addressData->getRegion() : '' ?>"
                       title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                       class="b2b-input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="b2b-field b2b-zip b2b-required">
            <label class="b2b-label" for="zip">
                <span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span>
            </label>
            <div class="b2b-control">
                <input type="text"
                       name="postcode"
                       value="<?= $block->escapeHtmlAttr(($addressData) ? $addressData->getPostcode() : '') ?>"
                       title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                       id="b2b-zip"
                       class="b2b-validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="b2b-field b2b-country b2b-required">
            <label class="b2b-label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="b2b-control">
                <?= $block->getCountryHtmlSelect(($addressData) ? $addressData->getCountryId() : null) ?>
            </div>
        </div>

        <br/>
        <div class="b2b-field b2b-billing">
            <input type="checkbox" id="b2b-primary_billing" name="is_billing" value="1" class="b2b-checkbox" <?= ($addressData && $addressData->getIsBilling()) ? 'checked' : '' ?>>
            <label class="b2b-label" for="primary_billing">
                <span><?= $block->escapeHtml(__('Set as Default Billing Address')) ?></span>
            </label>
        </div>
        <div class="b2b-field b2b-shipping">
            <input type="checkbox" id="b2b-primary_shipping" name="is_shipping_default" value="1" class="b2b-checkbox" <?= ($addressData && $addressData->getIsShippingDefault()) ? 'checked' : '' ?>>
            <label class="b2b-label" for="primary_shipping">
                <span><?= $block->escapeHtml(__('Set as Default Shipping Address')) ?></span>
            </label>
        </div>

    </fieldset>
    <div class="b2b-actions-toolbar">
        <input type="hidden" name="address_id" id="b2b-address_id" value="<?php echo $block->getIdAddress() ?>" >
        <div class="b2b-primary">
            <button type="submit" class="b2b-primary action" data-action="save-address" title="Save Address">
                <span><?php /* @escapeNotVerified */ echo __('Save') ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#b2b-region_id",
                "regionInputId": "#b2b-region",
                "postcodeId": "#b2b-zip",
                "form": "#b2b-form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= ($addressData) ? $addressData->getRegionId() : (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>