<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Tigren\CompanyAccount\Block\Customer\Create
 */
?>
<?php echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra')?>
<form class="b2b-form-create-user" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="b2b-form-validate" enctype="multipart/form-data" autocomplete="off">
    <fieldset class="b2b-info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="b2b-legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend><br>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
<!--        --><?php //if ($block->isNewsletterEnabled()): ?>
<!--            <div class="b2b-field choice newsletter">-->
<!--                <input type="checkbox" name="is_subscribed" title="--><?php ///* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?><!--" value="1" id="b2b-is_subscribed"--><?php //if ($block->getFormData()->getIsSubscribed()): ?><!-- checked="checked"--><?php //endif; ?><!-- class="b2b-checkbox">-->
<!--                <label for="is_subscribed" class="b2b-label"><span>--><?php ///* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?><!--</span></label>-->
<!--            </div>-->
<!--            --><?php ///* Extensions placeholder */ ?>
<!--            --><?php //echo $block->getChildHtml('customer.form.register.newsletter')?>
<!--        --><?php //endif ?>
        <div class="b2b-field">
            <label for="job_title" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Job Title') ?></span></label>
            <div class="b2b-control">
                <input type="text" name="job_title"  id="b2b-job_title" title="<?php /* @escapeNotVerified */ echo __('Job Title') ?>" class="b2b-input-text">
            </div>
        </div>
        <div class="b2b-field b2b-required">
            <label for="phone_number" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Phone') ?></span></label>
            <div class="b2b-control">
                <input type="text" name="phone_number"  id="b2b-phone_number" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="b2b-input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="b2b-field b2b-required">
            <label for="is_admin" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Permissions') ?></span></label>
            <div class="b2b-control">
            <select name="is_admin" id="b2b-is-admin" data-role="is-admin" title="<?php /* @escapeNotVerified */ echo __('Is Admin') ?>">
                <option value="0">User</option>
                <option value="1">Admin</option>
            </select>
            </div>
<!--            <input type="checkbox" name="is_admin" id="b2b-is-admin" data-role="is-admin" value="1" title="--><?php ///* @escapeNotVerified */ echo __('Is Admin') ?><!--" class="b2b-checkbox" />-->
<!--            <label class="b2b-label" for="is-admin"><span>--><?php ///* @escapeNotVerified */ echo __('Is Admin') ?><!--</span></label>-->
        </div>
        <div class="b2b-field b2b-required">
            <label for="is_active" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Active') ?></span></label>
            <div class="b2b-control">
            <select name="is_active" id="b2b-is_active" title="<?php /* @escapeNotVerified */ echo __('Active') ?>">
                <option value="1">Yes</option>
                <option value="2">No</option>
            </select>
            </div>
        </div>
        <div class="b2b-field" style="display: none;">
            <input type="checkbox" name="enable_enter_shipping_address" id="b2b-enable-enter-shipping-address" data-role="enable-enter-shipping-address" value="1" title="<?php echo __('Enable Enter Shipping Address') ?>" class="b2b-checkbox" />
            <label class="b2b-label" for="enable-enter-shipping-address"><span><?php echo __('Enable Enter Shipping Address') ?></span></label>
        </div>
        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
    </fieldset>
    <?php if ($block->getShowAddressFields()): ?>
        <fieldset class="b2b-address">
            <legend class="b2b-legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />
            <div class="b2b-field company">
                <label for="company" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                <div class="b2b-control">
                    <input type="text" name="company" id="b2b-company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="b2b-input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                </div>
            </div>
            <div class="b2b-field">
                <label for="telephone" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                <div class="b2b-control">
                    <input type="text" name="telephone" id="b2b-telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="b2b-input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                </div>
            </div>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="b2b-field b2b-required">
                <label for="street_1" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                <div class="b2b-control">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="b2b-street_1" class="b2b-input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                    <div class="b2b-nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="b2b-field additional">
                                <label class="b2b-label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                                </label>
                                <div class="b2b-control">
                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="b2b-street_<?php /* @escapeNotVerified */ echo $_i ?>" class="b2b-input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="b2b-field b2b-required">
                <label for="city" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                <div class="b2b-control">
                    <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="b2b-input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="b2b-city">
                </div>
            </div>

            <div class="b2b-field b2b-required">
                <label for="region_id" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                <div class="b2b-control">
                    <select id="b2b-region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="b2b-validate-select" style="display:none;">
                        <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                    </select>
                    <input type="text" id="b2b-region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="b2b-input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                </div>
            </div>

            <div class="b2b-field b2b-required">
                <label for="zip" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
                <div class="b2b-control">
                    <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="b2b-zip" class="b2b-input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                </div>
            </div>

            <div class="b2b-field b2b-required">
                <label for="country" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                <div class="b2b-control">
                    <?php echo $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>
    <fieldset class="b2b-fieldset account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="b2b-legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend><br>
        <div class="b2b-field b2b-required">
            <label for="email_address" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="b2b-control">
                <input type="email" name="email" autocomplete="email" id="b2b-email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="b2b-input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="b2b-field b2b-required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label for="password" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
            <div class="b2b-control">
                <input type="password" name="password" id="b2b-password"
                       title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                       class="b2b-input-text"
                       data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="b2b-password-strength-meter-container" data-role="password-strength-meter" >
                    <div id="b2b-password-strength-meter" class="b2b-password-strength-meter">
                        <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                        <span id="b2b-password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                        </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="b2b-field b2b-required">
            <label for="password-confirmation" class="b2b-label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
            <div class="b2b-control">
                <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="b2b-password-confirmation" class="b2b-input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="b2b-actions-toolbar">
        <div class="b2b-primary">
            <button type="submit" class="b2b-action submit primary" title="<?php /* @escapeNotVerified */ echo __('Create a User') ?>"><span><?php /* @escapeNotVerified */ echo __('Create a User') ?></span></button>
        </div>
        <div class="b2b-secondary">
            <a class="b2b-action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
        </div>
    </div>
</form>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="b2b-' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
