<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Tigren\CompanyAccount\Block\Customer\Edit $block */
?>
<?php
//    $enableEnterShippingAddress = $block->getCustomer()->getCustomAttribute('enable_enter_shipping_address')->getValue();
?>
<form class="form form-edit-user form-edit-account" action="<?php /* @escapeNotVerified */
echo $block->getUrl('companyaccount/account/editPost') ?>" method="post" id="form-validate"
      enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?php echo $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?php /* @escapeNotVerified */
                echo __($block->getUserTitleEdit()) ?></span>
            <?php if ($block->isAdminOfAccount() == 1): ?>
                <span class="user-permission" style="margin-left: 20px"><?php /* @escapeNotVerified */ echo __('Admin') ?></span>
            <?php else: ?>
                <span class="user-permission" style="margin-left: 20px"><?php /* @escapeNotVerified */ echo __('User') ?></span>
            <?php endif; ?>
        </legend>
        <br>
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

        <div class="field" style="display: none">
            <label class="label" for="enable_enter_shipping_address">
                <span><?php /* @escapeNotVerified */
                    echo __('Enable Enter Shipping Address') ?></span>
            </label>
            <div class="control">
                <select id="enable_enter_shipping_address" name="enable_enter_shipping_address"
                        title="<?= $block->escapeHtml(__('Enable Enter Shipping Address')) ?>" class="validate-select">
                    <option value="1"><?= $block->escapeHtml(__('Enable.')) ?></option>
                    <option value="0" selected><?= $block->escapeHtml(__('Disable.')) ?></option>
                </select>
            </div>
        </div>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <?php if ($block->isAdminOfAccount() == 0): ?>
            <div class="field">
                <label for="job_title" class="label"><span><?php /* @escapeNotVerified */
                        echo __('Job Title') ?></span></label>
                <div class="control">
                    <input type="text" name="job_title" id="job_title" value="<?php echo $block->getUserJobTitle(); ?>"
                           title="<?php /* @escapeNotVerified */
                           echo __('Job Title') ?>" class="input-text">
                </div>
            </div>
            <div class="field required">
                <label for="phone_number" class="label"><span><?php /* @escapeNotVerified */
                        echo __('Phone') ?></span></label>
                <div class="control">
                    <input type="text" name="phone_number" id="phone_number"
                           value="<?php echo $block->getUserPhoneNumber(); ?>" title="<?php /* @escapeNotVerified */
                    echo __('Phone') ?>" class="input-text" data-validate="{required:true}">
                </div>
            </div>
        <?php endif ?>
        <div class="field required" style="display: none">
            <label for="is_active" class="label"><span><?php /* @escapeNotVerified */
                    echo __('Active') ?></span></label>
            <select name="is_active" id="is_active" title="<?php /* @escapeNotVerified */
            echo __('Active') ?>">
                <option value="1"
                    <?php if ($block->getUserIsActive() == 1): ?>
                        selected="selected"
                    <?php endif ?>
                >Yes
                </option>
                <option value="2"
                    <?php if ($block->getUserIsActive() == 2): ?>
                        selected="selected"
                    <?php endif ?>
                >No
                </option>
            </select>
        </div>
        <div class="field required">
            <label for="is_admin" class="label"><span><?php /* @escapeNotVerified */
                    echo __('Permissions') ?></span></label>
            <div class="control">
                <select name="is_admin" id="is-admin" data-role="is-admin" title="<?php /* @escapeNotVerified */
                echo __('Is Admin') ?>">
                    <option value="0"
                        <?php if ($block->isAdminOfAccount() == 0): ?> selected="selected"<?php endif; ?>
                    >User
                    </option>
                    <option value="1"
                        <?php if ($block->isAdminOfAccount() == 1): ?> selected="selected"<?php endif; ?>
                    >Admin
                    </option>
                </select>
            </div>
        </div>

        <div class="field required email">
            <label for="email" class="label"><span><?php /* @escapeNotVerified */
                    echo __('Email') ?></span></label>
            <div class="control">
                <input type="text" name="email" id="email"
                       value="<?php echo $block->getUserEmail(); ?>" title="<?php /* @escapeNotVerified */
                echo __('Email') ?>" class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div style="display: none">
            <div class="field choice">
                <input type="checkbox" checked="checked" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
                <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
            </div>
            <div class="field choice">
                <input type="checkbox" checked="checked" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset password" style="display: block">
        <legend class="legend"><span data-title="change-email-password"><?php /* @escapeNotVerified */
                echo __('Change Password') ?></span></legend>
        <br>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?php /* @escapeNotVerified */
                    echo __('Current Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password"
                       data-input="current-password" autocomplete="off"/>
            </div>
        </div>
        <div class="field new password required" data-container="new-password"
             data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?php /* @escapeNotVerified */
                    echo __('New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                       data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                       data-input="new-password"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off"/>
                <div id="password-strength-meter-container" data-role="password-strength-meter">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php /* @escapeNotVerified */
                        echo __('Password Strength'); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?php /* @escapeNotVerified */
                            echo __('No Password'); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */
                    echo __('Confirm New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                       data-input="confirm-password"
                       autocomplete="off"/>
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */
            echo __('Save') ?>"><span><?php /* @escapeNotVerified */
                    echo __('Save') ?></span></button>
        </div>
        <input type="hidden" name="userId" id="userId" value="<?php echo $block->getUserId() ?>">
        <div class="secondary">
            <a class="action back"
               href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */
                    echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function ($) {
        var dataForm = $('#form-validate');
        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function (error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
            <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        });

    });
</script>
