<?php /**@var Tigren\CompanyAccount\Block\Adminhtml\Account\Edit\Tab\Customer\AssignActionCustomer $block **/ ?>
<form class="admin__scope-old"
      action=""
      method="post"
      id="new-assign-customer-form-validate"
      enctype="multipart/form-data"
      autocomplete="off"
      novalidate="novalidate">
    <fieldset class="fieldset admin__fieldset ">
        <legend class="legend"><span>Customers</span></legend><br>
        <?php echo $block->getAssignCustomerActionTabBlock()->toHtml() ?>
    </fieldset>
</form>
