<?php $orders = $block->getOrders(); ?>
<?php if (count($orders)): ?>
<?php echo $block->getChildHtml('info'); ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                <th scope="col" class="col name"><?php /* @escapeNotVerified */ echo __('Name') ?></th>
                <th scope="col" class="col email"><?php /* @escapeNotVerified */ echo __('Email') ?></th>
                <?php /* @noEscape */ echo $block->getChildHtml('extra.column.header');?>
                <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Ship To') ?></th>
                <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
                <?php
                foreach ($orders as $order): ?>
                        <tr>
                            <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $order->getExtOrderId() ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($order->getCreatedAt()) ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Name')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $order->getCustomerFirstName() ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Email')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $order->getCustomerEmail() ?></td>
                            <?php $extra = $block->getChildBlock('extra.container'); ?>
                            <?php if ($extra): ?>
                                <?php $extra->setOrder($order); ?>
                                <?php /* @noEscape */ echo $extra->getChildHtml() ?>
                            <?php endif; ?>
                            <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?php echo $order->getShippingAddress() ? $block->escapeHtml($order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $order->formatPrice($order->getGrandTotal()) ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $order->getStatusLabel() ?></td>
                            <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($order) ?>" class="action view">
                                    <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>

            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('Your users have placed no orders.'); ?></span></div>
<?php endif ?>






