<?php
$orders = $block->getOrders();
$checkAccount = $block->getAccountId();
?>
<?php if (count($orders)): ?>
    <?php echo $block->getChildHtml('info'); ?>
    <div class="b2b-tag-top">
        <div class="b2b-tag-top-right">
            <div class="b2b-field">
            <select id="b2b-orderId" class="b2b-orderId">
                    <?php if(!empty($checkAccount)): ?><option value="companyorder">View All Orders for <?php echo $block->getAccountName() ?></option><?php endif; ?>
                    <option value="myorder">View My Orders</option>
                </select>
            </div>
        </div>
        <div class="b2b-filterdate" style="overflow: hidden">
            <div class="b2b-field-overview-required" data-role="filter-form" id="b2b-date_range">
                <div class="b2b-orders-input">
                    <div class="b2b-field">
                        <label class="b2b-label"><span><?php /* @escapeNotVerified */echo __('From: ') ?></span></label>
                        <div class="b2b-control">
                            <input placeholder="dd/mm/yyyy" class="b2b-input-text orders-required-entry" type="text" id="b2b-date_from"
                                   name="from"/>
                        </div>
                    </div>

                    <div class="b2b-field">
                        <label class="b2b-label"><span><?php /* @escapeNotVerified */echo __('To: ') ?></span></label>
                        <div class="b2b-control">
                            <input placeholder="dd/mm/yyyy" class="b2b-input-text orders-required-entry" type="text" id="b2b-date_to"
                                   name="to"/>
                        </div>
                    </div>
                    <hr class="b2b-clear-both-invisible">
                </div>
                <div id="b2b-date_range_orders-button">
                <div class="b2b-actions-toolbar">
                    <div class="b2b-primary">
                        <button id="b2b-search_date_range" class="action"><?php /* @escapeNotVerified */echo __('Search') ?></button>
                    </div>
                    <div class="b2b-secondary">
                        <button id="b2b-reset_date" class="action"><?php /* @escapeNotVerified */echo __('Reset') ?></button>
                    </div>
                </div>
                </div>
            </div>
        </div>

    </div>
    <div class="b2b-clearfix"></div>
    <div class="b2b-table-wrapper orders-history">
        <table class="b2b-data table table-order-items history" id="b2b-my-orders-table">
            <caption class="b2b-table-caption"><?php /* @escapeNotVerified */
                echo __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="b2b-col id"><?php /* @escapeNotVerified */
                    echo __('Order#') ?></th>
                <th scope="col" class="b2b-col date"><?php /* @escapeNotVerified */
                    echo __('Date') ?></th>
                <th scope="col" class="b2b-col name"><?php /* @escapeNotVerified */
                    echo __('Name') ?></th>
                <th scope="col" class="b2b-col email"><?php /* @escapeNotVerified */
                    echo __('Email') ?></th>
                <?php /* @noEscape */
                echo $block->getChildHtml('extra.column.header'); ?>
                <th scope="col" class="b2b-col shipping"><?php /* @escapeNotVerified */
                    echo __('Ship To') ?></th>
                <th scope="col" class="b2b-col total"><?php /* @escapeNotVerified */
                    echo __('Total') ?></th>
                <th scope="col" class="b2b-col status"><?php /* @escapeNotVerified */
                    echo __('Status') ?></th>
                <th scope="col" class="b2b-col status"><?php /* @escapeNotVerified */
                    echo __('Action') ?></th>

            </tr>
            </thead>
            <tbody id="b2b-order_content">
            <!--Return Content-->
            <?php foreach ($block->getOrders() as $order): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>"
                        class="b2b-col id"><?php /* @escapeNotVerified */
                        echo $order->getExtOrderId() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>"
                        class="b2b-col date"><?php /* @escapeNotVerified */
                        echo $block->formatDate($order->getCreatedAt()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Name')) ?>"
                        class="b2b-col date"><?php /* @escapeNotVerified */
                        echo $order->getCustomerFirstName() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Email')) ?>"
                        class="b2b-col date"><?php /* @escapeNotVerified */
                        echo $order->getCustomerEmail() ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra): ?>
                        <?php $extra->setOrder($order); ?>
                        <?php /* @noEscape */
                        echo $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>"
                        class="b2b-col shipping"><?php echo $order->getShippingAddress() ? $block->escapeHtml($order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>"
                        class="b2b-col total"><?php /* @escapeNotVerified */
                        echo $order->formatPrice($order->getGrandTotal()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>"
                        class="b2b-col status"><?php /* @escapeNotVerified */
                        echo $order->getStatusLabel() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="b2b-col actions">
                        <a href="<?php /* @escapeNotVerified */
                        echo $block->getViewUrl($order) ?>" class="b2b-action view">
                            <span><?php /* @escapeNotVerified */
                                echo __('View Order') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            <!--End Return Content-->
            </tbody>
        </table>
    </div>

<?php else: ?>
    <div class="b2b-message empty"><span><?php echo __('Your users have placed no orders.'); ?></span></div>
<?php endif ?>

<script>
    require([
        "jquery",
        "mage/calendar"
    ], function ($) {
        jQuery(document).ready(function () {
            $("#b2b-date_range").dateRange({
                buttonText: "<?php echo __('Select Date') ?>",
                from: {
                    id: "b2b-date_from"
                },
                to: {
                    id: "b2b-date_to"
                }
            });
            //search all orders
            jQuery('#b2b-search-all-orders-buttom').click(function () {
                jQuery('#b2b-default').attr('selected', 'selected');
                jQuery('#b2b-date_from').val('');
                jQuery('#b2b-date_to').val('');
                var search = jQuery('#b2b-search-orders-all-input').val();
                var role = jQuery('#b2b-orderId').val();
                if (search === '') {
                    location.reload()
                }
                var url = "<?php echo $block->getBaseUrl() . 'companyaccount/result/searchallorder/' ?>";
                jQuery.ajax({
                    url: url,
                    type: 'POST',
                    data: {search: search, role: role},
                    showLoader: true,
                    cache: false
                }).done(function (response) {
                    jQuery('#order_content').html(response.response);
                });
                return false;
            });
            //search by select role order
            $('#b2b-orderId').change(function () {
                jQuery('#b2b-search-orders-all-input').val('');
                jQuery('#b2b-default').attr('selected', 'selected');
                jQuery('#b2b-date_from').val('');
                jQuery('#b2b-date_to').val('');
                var value = $(this).val();
                var url = "<?php echo $block->getBaseUrl() . 'companyaccount/result/order/';?>";
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {'data': value},
                    showLoader: true,
                    cache: false,
                    // dataType: 'json',
                }).done(function (response) {
                    $('#b2b-order_content').html(response);
                });
                return false;
            });
            jQuery('#b2b-date_from').click(function () {
                jQuery('#b2b-default').attr('selected', 'selected');
            jQuery('#b2b-date_to').click(function () {
                jQuery('#b2b-default').attr('selected', 'selected');
            });
            //search by date range
            jQuery('#b2b-search_date_range').click(function () {
                jQuery('#b2b-search-orders-all-input').val('');
                jQuery('#b2b-default').attr('selected', 'selected');
                var from_date = jQuery('#b2b-date_from').val();
                var to_date = jQuery('#b2b-date_to').val();
                var role = jQuery('#b2b-orderId').val();
                if (from_date === '' && to_date === '') {
                    location.reload();
                }
                var url = "<?php echo $block->getBaseUrl() . 'companyaccount/result/daterange/' ?>";
                jQuery.ajax({
                    url: url,
                    type: 'POST',
                    data: {from_date: from_date, to_date: to_date, role: role},
                    showLoader: true,
                    cache: false
                }).done(function (response) {
                    jQuery('#b2b-order_content').html(response.response);
                });
                return false;
            });
            //search by past time
            jQuery('#b2b-select-time').change(function () {
                jQuery('#b2b-search-orders-all-input').val('');
                jQuery('#b2b-date_from').val('');
                jQuery('#b2b-date_to').val('');
                var value = jQuery(this).val();
                var role = jQuery('#b2b-orderId').val();
                if (value === '') {
                    location.reload();
                }
                var url = "<?php echo $block->getBaseUrl() . 'companyaccount/result/pasttime/' ?>";
                jQuery.ajax({
                    url: url,
                    type: 'POST',
                    data: {value: value, role: role},
                    showLoader: true,
                    cache: false
                }).done(function (response) {
                    jQuery('#b2b-order_content').html(response.response);
                });
                return false;
            });
            //reset
            jQuery('#b2b-reset_date').click(function () {
                jQuery('#b2b-date_from').val('');
                jQuery('#b2b-date_to').val('');
                var role = jQuery('#b2b-orderId').val();

                var url = "<?php echo $block->getBaseUrl() . 'companyaccount/result/order/';?>";
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {'data': role},
                    showLoader: true,
                    cache: false,
                    // dataType: 'json',
                }).done(function (response) {
                    $('#b2b-order_content').html(response);
                });
                return false;
            });
        });
    });
</script>
