<?php
/** @var \Tigren\CompanyAccount\Block\Order\Items $block */

use Magento\Framework\App\Action\Action;

?>

<?php
$_order = $block->getOrder();
$totals = $block->getChildHtml('order_totals');
$payment = $_order->getPayment()->getMethodInstance()->getTitle();
$odItems = $_order->getAllItems();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_productCollection = $block->getLoadedProductCollection();
?>
    <div class="b2b-order-table-content">
        <div class="b2b-order-table-1">
            <table>
                <tr>
                    <th><legend class="b2b-legend"><span><?= __('Delivery Address') ?></span></legend></th>
                    <th><legend class="b2b-legend"><span><?= __('Payment Method') ?></span></legend></th>
                </tr>
                <tr>
                    <td><?= $block->getFormattedAddress($_order->getShippingAddress()) ?></td>
                    <td><?= $payment ?></td>
                </tr>
            </table>
        </div>
        <div class="b2b-order-table-2">
            <table style="margin-bottom: -15px">
                <th><legend class="b2b-legend"><span><?= __('Payment Method') ?></span></legend></th>
            </table>
            <?= $totals ?>
        </div>
    </div><div class="b2b-clearfix"></div>
    <div class="b2b-order-delevired">
        <div class="b2b-order-delevired-col-8">
            <div class="b2b-order-delevired-col-4">
                <div class="b2b-actions-toolbar">
                    <div class="b2b-secondary">
                    <button class="b2b-track-package action"><a class="b2b-action-button"
                                                     href="<?php echo $block->getUrlTracking($_order) ?>">Track
                            Package</a></button>
                    <?php if (!empty($block->isModuleEnabled())): ?>
                        <button class="b2b-replace-items action"><a class="b2b-action-button"
                                                         href="<?php echo $block->getRmaLink($_order); ?>">Return or
                                Replace Items</a></button>
                    <?php endif; ?>
                    </div>
                </div>
                    <hr>
                </div>
            <legend class="b2b-legend"><span>Order Items</span></legend>
            <div class="b2b-" style="width: 100%;clear: both;overflow: hidden;">
                <div class="b2b-order-products wrapper">
                    <ol class="b2b-order-products">
                        <div class="b2b-order-product-item-info">
                            <?php foreach ($_productCollection as $_product): ?>
                                <?php foreach ($odItems as $odItem): ?>
                                    <?php $_product = $block->getProductId($odItem->getProductId()); ?>
                                    <div class="b2b-box-order-product">
                                        <div class="b2b-order-image" style="float: left">
                                            <a href="<?= $_product->getProductUrl() ?>"
                                               class="b2b-product-item-photo">
                                                <img class="b2b-order-image-product"
                                                     src="<?php echo $block->getProductImageUrl($_product, 'category'); ?>"
                                                     alt="" width="160px" height="auto"> </a>
                                        </div>
                                        <div class="b2b-order-product-item-details">
                                            <div class="b2b-order-product-item-name">
                                                <strong class="b2b-order-product-item-name">
                                                    <a class="b2b-order-product-item-link"
                                                       href="<?= /* @escapeNotVerified */
                                                       $_product->getProductUrl() ?>">
                                                        <?= /* @escapeNotVerified */
                                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                                    </a>
                                                </strong>
                                                <span class="b2b-order-price">
                                                <?php echo /* @escapeNotVerified */
                                                $block->getProductPrice($_product); ?>
                                            </span>
                                            </div>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="company-tocart-form"
                                                      action="<?php /* @escapeNotVerified */
                                                      echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */
                                                    echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?php /* @escapeNotVerified */
                                                           echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit" title="<?php echo __('Buy it again'); ?>"
                                                            class="b2b-primary">
                                                        <span class="b2b-buy-it-again"><?php /* @escapeNotVerified */
                                                            echo __('Buy it again') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="b2b-available"><span><?php /* @escapeNotVerified */
                                                            echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="b2b-unavailable"><span><?php /* @escapeNotVerified */
                                                            echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="b2b-clearfix"></div>
                                    </div>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </div>
                    </ol>
                </div>
                <div class="b2b-clearfix"></div>
            </div>
        </div>
    </div>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "[data-role=company-tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

    </script>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function () {
            var maxHeight = 100;
            $(".order-product-item-details").css("max-height", "250px");
            $(".order-product-item-details").each(function(){
                if($(this).height() > maxHeight){
                    maxHeight = $(this).height();
                }
            });
            $(".order-product-item-details").height(maxHeight);
        });
    });
</script>