<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Sales\Block\Order\View*/?>

<?php $_history = $block->getOrder()->getVisibleStatusHistory() ?>
<?php if (count($_history)): ?>
    <div class="b2b-block-order-details-comments">
        <div class="b2b-block-title"><strong><?= /* @escapeNotVerified */ __('About Your Order') ?></strong></div>
        <div class="b2b-block-content">
            <dl class="b2b-order-comments">
                <?php foreach ($_history as $_historyItem): ?>
                    <dt class="b2b-comment-date"><?= /* @escapeNotVerified */ $block->formatDate($_historyItem->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?></dt>
                    <dd class="b2b-comment-content"><?= $block->escapeHtml($_historyItem->getComment()) ?></dd>
                <?php endforeach; ?>
            </dl>

        </div>
    </div>
<?php endif; ?>
