<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="b2b-block-dashboard-orders">
    <?php $_orders = $block->getOrders(); ?>
    <div class="b2b-block-title">
        <strong><?= /* @escapeNotVerified */ __('Recent Orders') ?></strong>
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <a class="b2b-view" href="<?= /* @escapeNotVerified */ $block->getUrl('sales/order/history') ?>">
                <span><?= /* @escapeNotVerified */ __('View All') ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="b2b-block-content">
        <?= $block->getChildHtml() ?>
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <div class="b2b-orders-recent">
                <table class="b2b-table-order-items" id="b2b-my-orders-table">
                    <caption class="b2b-table-caption"><?= /* @escapeNotVerified */ __('Recent Orders') ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="b2b-col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                        <th scope="col" class="b2b-col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                        <th scope="col" class="b2b-col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                        <th scope="col" class="b2b-col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                        <th scope="col" class="b2b-col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                        <th scope="col" class="b2b-col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($_orders as $_order): ?>
                        <tr>
                            <?php if (!empty($_order->getExtOrderId())): ?>
                                <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="b2b-col id"><?= /* @escapeNotVerified */ $_order->getExtOrderId() ?></td>
                            <?php else: ?>
                                <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="b2b-col id"><?= /* @escapeNotVerified */ $_order->getInCrementId() ?></td>
                            <?php endif ?>
                            <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="b2b-col date"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="b2b-col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="b2b-col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="b2b-col status"><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="b2b-col actions">
                                <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="b2b-view">
                                    <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                                </a>
                                <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                    $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                        ->getPostData($block->getReorderUrl($_order))
                                    ?>' class="b2b-order">
                                        <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
                                    </a>
                                <?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="b2b-message empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
        <?php endif; ?>
    </div>
</div>
