<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist $block */
?>

<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form class="b2b-form-wishlist-items" id="b2b-wishlist-view-form"
          data-mage-init='{"wishlist":{
          "addToCartUrl":<?= /* @noEscape */ $block->getItemAddToCartParams("%item%") ?>,
          "addAllToCartUrl":<?= /* @noEscape */ $block->getAddAllToCartParams() ?>,
          "commentString":""},
          "validation": {}}' action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId()])) ?>" method="post">
        <div class="b2b-actions-toolbar">
            <div class="b2b-primary">
                <?= $block->getChildHtml('control_buttons') ?>
            </div>
        </div>
        <?= $block->getChildHtml('top') ?>
        <?php if ($block->hasWishlistItems()): ?>
            <?= $block->getBlockHtml('formkey') ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
        <?php else: ?>
            <div class="b2b-message empty"><span><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></span></div>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>

    </form>
    <script id="b2b-form-tmpl" type="text/x-magento-template">
        <form id="b2b-wishlist-hidden-form" method="post" action="<%- data.url %>" class="b2b-no-display">
            <% if (data.qty) { %>
            <input name="qty" value="<%- data.qty %>">
            <% } %>

            <% if (data.item) { %>
            <input name="item" value="<%- data.item %>">
            <% } %>

            <% if (data.entity) { %>
            <input name="entity" value="<%- data.entity %>">
            <% } %>
        </form>
    </script>
<?php endif ?>
