<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="b2b-block-dashboard-addresses ">
    <legend class="b2b-legend">
        <span><?= $block->escapeHtml(__('Account Information')) ?></span>
        <a href="#" class="b2b-action-edit"><?= $block->escapeHtml(__('Edit')) ?></a>
    </legend>
    <div class="b2b-block-content">
        <div class="b2b-block-dashboard-info">
            <div class="b2b-box-logo-company">
                <div class="b2b-box-content">
                    <img title=""
                         alt=""
                         src="<?= $block->getAccountImage() ?>"
                         height="40px"/>
                </div>
            </div>
            <div class="b2b-box-company-detail-info">
                <?= $block->getAccountInfo() ?>
            </div>
        </div>
    </div>
</div>
<div class="b2b-block-dashboard-addresses">
    <legend class="b2b-legend">
        <span><?= $block->escapeHtml(__('Company Address')) ?></span>
    </legend>
    <div class="b2b-block-content">
        <div class="b2b-box-billing-address">
            <div class="b2b-box-content">
                <address>
                    <?= $block->getLegalAddress() ?>
                </address>
            </div>
        </div>
    </div>
</div>
<hr class="b2b-clear-both-invisible">
<div class="b2b-block-contact">
    <legend class="b2b-legend">
        <span><?= $block->escapeHtml(__('Contacts')) ?></span>
    </legend>
    <div class="b2b-block-content">
        <div class="b2b-box-admin-account">
            <label class="b2b-label">
                <span><?= $block->escapeHtml(__('Company Administrator')) ?></span>
            </label>
            <div class="b2b-controls">
                <address>
                    <select id="b2b-accountId">
                        <option>Select Admin</option>
                        <?php foreach ($block->getAllAdminAccount() as $admin): ?>
                            <option value = "<?php echo $admin['entity_id']; ?>"><?php echo $admin['lastname']." ".$admin['firstname']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <br/><br/>
                    <div id="b2b-dataResponse"></div>
                </address>
            </div>
        </div>
    </div>
</div>
<div class="b2b-block-payment-info">
    <legend class="b2b-legend">
        <span><?= $block->escapeHtml(__('Payment Information')) ?></span>
    </legend>
    <div class="b2b-block-content">
        <div class="b2b-box-billing-address">
            <label class="b2b-label">
                <?php if (!empty($block->availablePayOnAccount())): ?>
                    <span><?= $block->escapeHtml(__('Can Pay on Account')) ?></span>
                <?php else: ?>
                    <span><?= $block->escapeHtml(__('Cannot Pay on Account')) ?></span>
                <?php endif ?>
            </label>
        </div>
    </div>
</div>

<script>
    require(['jquery'],function(){
        jQuery(document).ready(function() {
            jQuery('#b2b-accountId').change(function(){
                var value = jQuery(this).val();
                var url = "<?php echo $block->getBaseUrl().'companyaccount/result/result/' ?>";
                jQuery.ajax({
                    url: url,
                    type: 'POST',
                    data: {value:value},
                    showLoader: true,
                    cache: false
                }).done(function(response) {
                    jQuery('#b2b-dataResponse').html(response);
                });
                return false;
            });
        });
    });
</script>
