<script>
    function ConfirmDelete() {
        var x = confirm("Are you sure you want to remove?");
        if (x)
            return true;
        else
            return false;
    }
</script>
<?php $listAddress = $block->getListAddress(); ?>
<?php if (!$listAddress->getSize()): ?>
    <div style="margin-top: 10px" class="message info empty">
        <span><?php echo __('There are no other addresses.'); ?></span></div>
<?php endif ?>
<div class="a-section a-spacing-double-large">
    <div class="a-row a-spacing-micro">
        <div class="a-column a-span4 a-spacing-none a-spacing-top-mini address-column">
            <a id="ya-myab-address-add-link" class="a-link-normal add-new-address-button"
               href="<?php /* @escapeNotVerified */
               echo $block->getActionUrl('addressCreate') ?>">
                <div class="a-box first-desktop-address-tile">
                    <div class="a-box-inner a-padding-extra-large">
                        <img class="add-new-address"
                             src='<?php echo $this->getViewFileUrl('Tigren_CompanyAccount::images/newaddress.jpg'); ?>'
                             alt="image-icon"/>
                        <h2 class="a-color-tertiary">Add Address</h2></div>
                </div>
            </a>
        </div>
        <?php if ($listAddress && $listAddress->getSize()): ?>
            <?php foreach ($listAddress as $address): ?>
                <div class="a-column a-span4 a-spacing-none a-spacing-top-mini address-column">
                    <div id="ya-myab-display-address-block-0" class="a-box a-spacing-none normal-desktop-address-tile">
                        <div class="a-box-inner a-padding-none">

                            <div class="a-section address-section-no-default">
                                <div class="a-row a-spacing-small">
                                    <ul class="a-unordered-list a-nostyle a-vertical">
                                        <li><span class="a-list-item"><h5 id="address-ui-widgets-FullName"
                                                                          class="id-addr-ux-search-text  a-text-bold"><?php echo $address->getFirstname() . ' ' . $address->getLastname(); ?></h5></span>
                                        </li>
                                        <li><span class="a-list-item"><span id="address-ui-widgets-AddressLineOne"
                                                                            class="id-addr-ux-search-text"><?php echo $address->getStreet() ?></span></span>
                                        </li>
                                        <li><span class="a-list-item"><span id="address-ui-widgets-CityStatePostalCode"
                                                                            class="id-addr-ux-search-text"><?php echo $address->getCity() ?></span></span>
                                        </li>
                                        <li><span class="a-list-item"><span id="address-ui-widgets-Country"
                                                                            class="id-addr-ux-search-text"><?php echo $address->getCompany() ?></span></span>
                                        </li>
                                        <li><span class="a-list-item"><span id="address-ui-widgets-PhoneNumber"
                                                                            class="id-addr-ux-search-text">Phone number: <?php echo $address->getTelephone() ?></span></span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="ya-myab-edit-address-desktop-row-0" class="a-row edit-address-desktop-link">

                        <a id="ya-myab-address-edit-btn-0" class="a-link-normal"
                           href="<?php echo $block->getActionUrl('addressEdit', $address->getId()) ?>">Edit </a>
                        &nbsp; | &nbsp;
                        <a id="ya-myab-address-delete-btn-0" onclick="return ConfirmDelete();"
                           class="a-link-normal action delete"
                           href="<?php echo $block->getActionUrl('deleteAddress', $address->getId()) ?>"><span
                                    class="a-declarative"
                                    data-action="a-modal"
                                    data-a-modal="{&quot;name&quot;:&quot;deleteAddressModal-0&quot;,&quot;width&quot;:&quot;400&quot;,&quot;header&quot;:&quot;Confirm Deletion&quot;}">Delete</span>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif ?>
    </div>
</div>