<script>
    function ConfirmUserDelete() {
        return confirm("Are you sure you want to delete this user?");
    }
</script>
<div class="actions-toolbar">
    <div class="primary">
        <button class="action submit primary" onclick="window.open('<?php /* @escapeNotVerified */
        echo $block->getActionUrl('create') ?>','_self')" title="<?php /* @escapeNotVerified */
        echo __('Add User') ?>"><span "><?php /* @escapeNotVerified */
            echo __('Add User') ?></span></button>
    </div>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span>Back</span></a>
    </div>
</div>
<?php $listUser = $block->getListUser(); ?>
<?php if ($listUser && $listUser->getSize()): ?>
    <br/>
    <div class="table-wrapper orders-history">
        <div class="data table table-manage-user history" id="my-orders-table">
            <?php foreach ($listUser as $user): ?>
                <?php $userId = $user->getId(); ?>
                <div class="user-item">
                    <div class="user-image"><img
                                src='<?php echo $this->getViewFileUrl('Tigren_CompanyAccount::images/profile.png'); ?>'
                                alt="image-icon" width="80" height="80"/>
                    </div>
                    <div class="col-fullname">
                        <?php if (!empty($block->isAdminOfAccount($userId))): ?>
                            <b class="is-admin">Administrator</b>
                        <?php endif ?>
                        <div class="col fullname">
                            <b><?php echo $user->getFirstname() . ' ' . $user->getLastname() ?></b>
                        </div>
                        <div><?php echo $user->getEmail() ?></div>
                    </div>
                    <div class="col actions col-actions" data-th="<?php echo $block->escapeHtml(__('Actions')) ?>">
                        <ul class="sub-user" style="list-style: none;">
                            <li>
                                <a href="<?php echo $block->getActionUrl('edit', $userId) ?>" class="action view">
                                    <span><?php echo __('Edit User') ?></span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getActionUrl('delete', $userId) ?>"
                                   onclick="return ConfirmUserDelete();" class="action delete">
                                    <span><?php echo __('Delete User') ?></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div style="margin-top: 10px" class="message info empty"><span><?php echo __('There are no other users.'); ?></span>
    </div>
<?php endif ?>
