<script>
    function ConfirmUserDelete() {
        return confirm("Are you sure you want to delete this user?");
    }
</script>
<div class="b2b-actions-toolbar">
    <div class="b2b-primary">
        <button class="action b2b-primary" onclick="window.open('<?php /* @escapeNotVerified */
        echo $block->getActionUrl('create') ?>','_self')" title="<?php /* @escapeNotVerified */
        echo __('Add User') ?>"><span "><?php /* @escapeNotVerified */
            echo __('Add User') ?></span></button>
    </div>
</div>
<?php $listUser = $block->getListUser(); ?>
<?php if ($listUser && $listUser->getSize()): ?>
    <div class="b2b-users">
        <div class="b2b-users-inner" id="b2b-users-table">
            <?php foreach ($listUser as $user): ?>
                <?php $userId = $user->getId(); ?>
                <div class="b2b-user-item">
                    <div class="b2b-user-image"><img
                                src='<?php echo $this->getViewFileUrl('Tigren_CompanyAccount::images/profile.png'); ?>'
                                alt="image-icon" width="80" height="80"/>
                    </div>
                    <div class="b2b-col-fullname">
                        <?php if (!empty($block->isAdminOfAccount($userId))): ?>
                            <b class="b2b-is-admin">Administrator</b>
                        <?php endif ?>
                        <div class="b2b-fullname">
                            <b><?php echo $user->getFirstname() . ' ' . $user->getLastname() ?></b>
                        </div>
                        <div><?php echo $user->getEmail() ?></div>
                    </div>
                    <div class="b2b-actions-toolbar b2b-col-actions" data-th="<?php echo $block->escapeHtml(__('Actions')) ?>">
                        <ul class="b2b-sub-user" style="list-style: none;">
                            <li>
                                <a href="<?php echo $block->getActionUrl('edit', $userId) ?>" class="b2b-action secondary view">
                                    <span><?php echo __('Edit User') ?></span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getActionUrl('delete', $userId) ?>"
                                   onclick="return ConfirmUserDelete();" class="b2b-action secondary delete">
                                    <span><?php echo __('Delete User') ?></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <hr class="b2b-clear-both-invisible">
                </div>
                <hr class="b2b-clear-both">
            <?php endforeach; ?>
        </div>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="b2b-order-products-toolbar"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div style="margin-top: 10px" class="b2b-empty"><span><?php echo __('There are no other users.'); ?></span>
    </div>
<?php endif ?>
