<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<?php if ($block->disableEdit() == 1): ?>
    <div class="b2b-block-dashboard-addresses">
        <div class="b2b-block-content">
            <div class="b2b-box-billing-address">
                <div class="b2b-box-content">
                    <?= $block->getAccountManager() ?>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>