<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Tigren\CompanyAccount\Block\Account\Dashboard\Info $block */

$account = $block->getAccount();
$default_img_url = $block->getViewFileUrl('Tigren_CompanyAccount::images/company_default.png');
$logoImgLink = !empty($account->getLogoImageLink()) ? $account->getLogoImageLink() : $default_img_url
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <?php if ($account): ?>
            <div class="box box-company-info">
                <div class="box-logo-company">
                    <div class="box-content">
                        <img title="<?php echo $account->getCompany() ?>"
                             alt="<?php echo $account->getCompany() ?>"
                             src="<?php echo $logoImgLink ?>"
                             height="40px"/>
                    </div>
                </div>
                <div class="box-company-detail-info">
                    <h2><?= 'Hello '. $block->escapeHtml($block->getName()) ?>, <br></h2>
                    <p><?= __($block->getTitleWelcomeCompany($account->getCompany()))?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
