<div class="block block-dashboard-menu">
    <div class="block-content">
        <div class="block-inner">
            <div class="account-block">
                <a href="<?php echo $this->getUrl('customer/account/edit')?>" class="menu-item">
                    <div class="box-content">
                            <i id="profile" class="material-icons">account_circle </i>
                            <h6><?= __('My Profile')?></h6>
                            <hr class="clear-both">
                            <p><?= __('View and edit your profile info')?></p>
                            <p class="menuLink">View Profile <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
            <div class="account-block">
                <a href="<?php echo $this->getUrl('companyaccount/order/history')?>" class="menu-item">
                    <div class="box-content">
                        <i id="orders" class="material-icons">card_giftcard</i>
                        <h6><?= __('My Orders')?></h6>
                        <hr class="clear-both">
                        <p><?= __('Track, return or buy new items')?></p>
                        <p class="menuLink">View Orders <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
            <div class="account-block">
                <a href="<?php echo $this->getUrl('apiquote')?>" class="menu-item">
                    <div class="box-content">
                        <i id="description" class="material-icons">description</i>
                        <h6><?= __('My Quotes')?></h6>
                        <hr class="clear-both">
                        <p><?= __('View your quotes')?></p>
                        <p class="menuLink">View Quotes <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
            <div class="account-block">
                <a href="<?php echo $this->getUrl('companyaccount/account/address/')?>" class="menu-item">
                    <div class="box-content">
                        <i id="location" class="material-icons">location_on</i>
                        <h6><?= __('Addresses')?></h6>
                        <hr class="clear-both">
                        <p><?= __('Edit addresses and delivery preferences')?></p>
                        <p class="menuLink">View Addresses <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
            <div class="account-block">
                <a href="<?php echo $this->getUrl('companyaccount/account/listuser/')?>" class="menu-item">
                    <div class="box-content">
                        <i id="users" class="material-icons">supervisor_account</i>
                        <h6><?= __('Manage Users')?></h6>
                        <hr class="clear-both">
                        <p><?= __('Add, delete or edit users')?></p>
                        <p class="menuLink">View Users <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
            <div class="account-block">
                <a href="<?php echo $this->getUrl('companyaccount/account/profile/')?>" class="menu-item">
                    <div class="box-content">
                        <i id="company" class="material-icons">business</i>
                        <h6><?= __('Company Details')?></h6>
                        <hr class="clear-both">
                        <p><?= __('View and edit your company details')?></p>
                        <p class="menuLink">View Company Details <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
            <div class="account-block">
                <a href="<?php echo $this->getUrl('companyaccount/account/profile/')?>" class="menu-item">
                    <div class="box-content">
                        <i id="rma" class="material-icons">layers</i>
                        <h6><?= __('RMA')?></h6>
                        <hr class="clear-both">
                        <p><?= __('Manage and request returns for your orders')?></p>
                        <p class="menuLink">Manage RMA <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
            <div class="account-block">
                <a href="<?php echo $this->getUrl('companyaccount/account/profile/')?>" class="menu-item">
                    <div class="box-content">
                        <i id="wishlist" class="material-icons">star_border</i>
                        <h6><?= __('Wishlist')?></h6>
                        <hr class="clear-both">
                        <p><?= __('View and manage your item wishlist')?></p>
                        <p class="menuLink">Manage Wishlist <i class="material-icons">call_made</i></p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
