<div class="b2b-block-dashboard-menu">
    <div class="b2b-block-content">
        <div class="b2b-block-inner">
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('customer/account/edit')?>" class="b2b-menu-item">
                                    <i id="b2b-profile" class="material-icons">account_circle</i>
                                    <h6><?= __('My Profile')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('View and edit your profile info.')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('customer/account/edit')?>"><i class="material-icons">keyboard_arrow_right</i> Change Password</a></span>
                                    <span><a href="<?php echo $this->getUrl('customer/account/edit')?>"><i class="material-icons">keyboard_arrow_right</i> Change Email Address</a></span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('companyaccount/order/history')?>" class="b2b-menu-item">
                                    <i id="b2b-orders" class="material-icons">card_giftcard</i>
                                    <h6><?= __('My Orders')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('Track, return or buy new items')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('companyaccount/order/history')?>"><i class="material-icons">keyboard_arrow_right</i> Order History</a></span>
                                    <span><a href="<?php echo $this->getUrl('companyaccount/order/history')?>"><i class="material-icons">keyboard_arrow_right</i> View An Order</a></span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('apiquote')?>" class="b2b-menu-item">
                                    <i id="b2b-description" class="material-icons">description</i>
                                    <h6><?= __('My Quotes')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('View your quotes')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('apiquote')?>"><i class="material-icons">keyboard_arrow_right</i> View All Quotes</a></span>
                                    <span><a href="<?php echo $this->getUrl('apiquote')?>"><i class="material-icons">keyboard_arrow_right</i> Find A Quote</a></span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('companyaccount/account/address/')?>" class="b2b-menu-item">
                                    <i id="b2b-location" class="material-icons">location_on</i>
                                    <h6><?= __('Addresses')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('Edit addresses and delivery preferences')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/address/')?>"><i class="material-icons">keyboard_arrow_right</i> Add An Address</a></span>
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/address/')?>"><i class="material-icons">keyboard_arrow_right</i> Edit an Address</a></span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('companyaccount/account/listuser/')?>" class="b2b-menu-item">
                                    <i id="b2b-users" class="material-icons">supervisor_account</i>
                                    <h6><?= __('Manage Users')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('Add, delete or edit users')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/create/')?>"><i class="material-icons">keyboard_arrow_right</i> Add A Users</a></span>
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/listuser/')?>"><i class="material-icons">keyboard_arrow_right</i> Delete A User</a></span>
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/listuser/')?>"><i class="material-icons">keyboard_arrow_right</i> Edit A User</a></span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('companyaccount/account/profile/')?>" class="b2b-menu-item">
                                    <i id="b2b-company" class="material-icons">business</i>
                                    <h6><?= __('Company Details')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('View and edit your company details')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/profile/')?>"><i class="material-icons">keyboard_arrow_right</i> View Account Information</a></span>
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/profile/')?>"><i class="material-icons">keyboard_arrow_right</i> View Company Address</a></span>
                                    <span><a href="<?php echo $this->getUrl('companyaccount/account/profile/')?>"><i class="material-icons">keyboard_arrow_right</i> View Payment Information</a></span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('returns/rma/list/')?>" class="b2b-menu-item">
                                    <i id="b2b-rma" class="material-icons">layers</i>
                                    <h6><?= __('RMA')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('Manage and request returns for your orders')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('returns/rma/new')?>"><i class="material-icons">keyboard_arrow_right</i> Request New Return</a></span>
                                    <span><a href="<?php echo $this->getUrl('returns/rma/list')?>"><i class="material-icons">keyboard_arrow_right</i> View My Returns</a></span>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="b2b-account-block">
                        <div class="b2b-box-content">
                            <div class="b2b-box-container">
                                <a href="<?php echo $this->getUrl('wishlist')?>" class="b2b-menu-item">
                                    <i id="b2b-wishlist" class="material-icons">star_border</i>
                                    <h6><?= __('Wishlist')?></h6>
                                </a>
                                <hr class="b2b-clear-both">
                                <p><?= __('View and manage your item wishlist')?></p>
                                <div class="b2bQuickLinks">
                                    <span><a href="<?php echo $this->getUrl('wishlist')?>"><i class="material-icons">keyboard_arrow_right</i> View Wishlist Items</a></span>
                                </div>
                            </div>
                        </div>
                </div>

            </div>
    </div>
</div>
