<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Tigren\CompanyAccount\Block\Account\Dashboard\Info $block */
?>
<?php $account = $block->getAccount(); ?>

<?php if ($account && !empty($account->getPublicNotes())): ?>
    <div class="b2b-company-public-notes">
        <i class="material-icons">error_outline</i>
        <p><?= $account->getPublicNotes() ?></p>
    </div>
<?php endif; ?>
